# Generated by Django 5.0 on 2023-12-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_venue_email_address_alter_venue_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Venue Address'),
        ),
    ]
